name: openlane-cts
fullname: OpenLane CTS
description: OpenLane clock tree synthesis step
category: "PD: CTS"

inputs:
  - design.odb

outputs:
  - 1-cts.log
  - 2-cts_sta.log
  - 3-resizer.log
  - reports
  - design.odb
  - design.def
  - design.sdc
  - metrics.csv

#-------------------------------------------------------------------------
# Commands
#-------------------------------------------------------------------------

commands:
  # Link inputs to OpenLANE
  - mkdir -p $OPENLANE_DIR/designs/$DESIGN/
  - ln -sf `pwd`/inputs/design.odb $OPENLANE_DIR/0
  # Run step
  - cd $OPENLANE_DIR
  - make run_step OPENLANE_STEP=cts
  - cd -
  # Link outputs from OpenLANE
  - rm -f outputs/*
  - ln -sf $OPENLANE_DIR/designs/$DESIGN/runs/$FLOW_RUNID/$STEP_NAME/logs/cts/1-cts.log outputs/1-cts.log
  - ln -sf $OPENLANE_DIR/designs/$DESIGN/runs/$FLOW_RUNID/$STEP_NAME/logs/cts/2-cts_sta.log outputs/2-cts_sta.log
  - ln -sf $OPENLANE_DIR/designs/$DESIGN/runs/$FLOW_RUNID/$STEP_NAME/logs/cts/3-resizer.log outputs/3-resizer.log
  - ln -sf `find $OPENLANE_DIR/designs/$DESIGN/runs/$FLOW_RUNID/$STEP_NAME/results/cts -name "*.odb"` outputs/design.odb
  - ln -sf `find $OPENLANE_DIR/designs/$DESIGN/runs/$FLOW_RUNID/$STEP_NAME/results/cts -name "*.def"` outputs/design.def
  - ln -sf `find $OPENLANE_DIR/designs/$DESIGN/runs/$FLOW_RUNID/$STEP_NAME/results/cts -name "*.sdc"` outputs/design.sdc
  - ln -sf $OPENLANE_DIR/designs/$DESIGN/runs/$FLOW_RUNID/$STEP_NAME/reports/cts/ outputs/reports
  - ln -sf $OPENLANE_DIR/designs/$DESIGN/runs/$FLOW_RUNID/$STEP_NAME/reports/metrics.csv outputs/metrics.csv
