#=========================================================================
# Cadence Genus Synthesis Optimization
#=========================================================================
# Author : Akash Levy
# Date   : November 1, 2023
#=========================================================================

fullname: Cadence Genus Synthesis Opt
category: Logic Synthesis
description: Run synthesis optimization using Cadence Genus
name: cadence-genus-syn-opt
container: silimate/eda-docker:latest

#-------------------------------------------------------------------------
# Inputs and Outputs
#-------------------------------------------------------------------------

inputs:
  - config/
  - flow/
  - syn_map.db

outputs:
  - config/
  - flow/
  - fv/
  - syn_opt.db
  - syn_opt.log

#-------------------------------------------------------------------------
# Commands
#-------------------------------------------------------------------------

commands:
  - cp inputs/flow/run_flow.tcl inputs/
  - cp inputs/config/*.tcl inputs/
  - genus -no_gui -f START.tcl -log outputs/syn_opt.log
  - cp -r inputs/config outputs/config
  - cp -r inputs/flow outputs/flow
  - mv dbs/* outputs/
  - mv fv/ outputs/
