#=========================================================================
# Cadence Conformal LEC
#=========================================================================
# Author : Akash Levy
# Date   : November 1, 2023
#=========================================================================

fullname: Cadence Conformal LEC
category: LEC
description: Runs Cadence Conformal logic equivance check (LEC)
name: cadence-conformal-lec
container: silimate/eda-docker:latest

#-------------------------------------------------------------------------
# Inputs and Outputs
#-------------------------------------------------------------------------

inputs:
  - design.v.gz
  - fv/
  - rtl/

outputs:
  - lec.syn_map.ckpt
  - lec.syn_map.log
  - lec.syn_opt.ckpt
  - lec.syn_opt.log
  - rpts/

#-------------------------------------------------------------------------
# Commands
#-------------------------------------------------------------------------

commands:
  - mkdir -p outputs/rpts
  - mkdir -p logs
  - cp -Lrf inputs/fv .
  - sed -i 's#dbs/syn_opt\.cdb/cmn/.*\.v\.gz#inputs/design.v.gz#' fv/*/lec.syn_opt.do
  - lec -lp -nogui -dofile fv/*/lec.syn_map.do -log logs/lec.syn_map.log
  - lec -lp -nogui -dofile fv/*/lec.syn_opt.do -log logs/lec.syn_opt.log
  - mv logs/*.log outputs
  - mv *.rpt outputs/rpts
  - mv fv/*/*.ckpt outputs/
