#=========================================================================
# Cadence Conformal LEC
#=========================================================================
# Author : Akash Levy
# Date   : November 1, 2023
#=========================================================================

fullname: Cadence Conformal LEC
category: LEC
description: Runs Cadence Conformal logic equivance check (LEC)
name: cadence-conformal-lec
container: silimate/eda-docker:latest

#-------------------------------------------------------------------------
# Inputs and Outputs
#-------------------------------------------------------------------------

inputs:
  - fv/

outputs:
  - lec.log

#-------------------------------------------------------------------------
# Commands
#-------------------------------------------------------------------------

commands:
  - mkdir -p outputs
  - cd inputs/fv/
  - lec -lp -nogui -dofile lec.syn_map.do -log ../../outputs/lec.syn_map.log
  - lec -lp -nogui -dofile lec.syn_opt.do -log ../../outputs/lec.syn_opt.log
