#=========================================================================
# Cadence Conformal LEC Flow
#=========================================================================
# Author : Akash Levy
# Date   : November 1, 2023
#=========================================================================

fullname: Cadence Conformal LEC Flow
category: LEC
description: Runs Cadence Conformal LEC flow
name: cadence-conformal-lec
container: silimate/eda-docker:latest

#-------------------------------------------------------------------------
# Inputs and Outputs
#-------------------------------------------------------------------------

inputs:
  - fv/

outputs:
  - lec.log

#-------------------------------------------------------------------------
# Commands
#-------------------------------------------------------------------------

commands:
  - cd inputs/fv/
  - lec -no_gui -dofile lec.syn_map.do -log ../../outputs/lec.syn_map.log
  - lec -no_gui -dofile lec.syn_opt.do -log ../../outputs/lec.syn_opt.log
