#=========================================================================
# Cadence Conformal LEC
#=========================================================================
# Author : Akash Levy
# Date   : November 1, 2023
#=========================================================================

fullname: Cadence Conformal LEC
category: LEC
description: Runs Cadence Conformal logic equivance check (LEC)
name: cadence-conformal-lec
container: silimate/eda-docker:latest

#-------------------------------------------------------------------------
# Inputs and Outputs
#-------------------------------------------------------------------------

inputs:
  - design.v.gz
  - fv/
  - rtl/

outputs:
  - ckpts/
  - logs/
  - rpts/

#-------------------------------------------------------------------------
# Commands
#-------------------------------------------------------------------------

commands:
  - mkdir -p outputs/ckpts
  - mkdir -p outputs/logs
  - mkdir -p outputs/rpts
  - cp -Lrf inputs/fv .
  - for dofile in fv/*/*.do; do sed -i 's#dbs/[a-z_]*\.cdb/cmn/.*\.v\.gz#inputs/design.v.gz#' $dofile; done
  - for dofile in fv/*/*.do; do lec -lp -nogui -dofile $dofile -log outputs/logs/`basename $dofile`.log; done
  - mv fv/*/*.ckpt outputs/ckpts/
  - mv *.rpt outputs/rpts/
