name: openlane-route
fullname: OpenLane Route
description: OpenLane routing step
category: "PD: Route"

inputs:
  - design.odb

outputs:
  - 1-resizer_design.log
  - 2-rsz_design_sta.log
  - 3-resizer_timing.log
  - 4-rsz_timing_sta.log
  - 5-global_write_netlist.log
  - 7-grt_sta.log
  - 8-fill.log
  - 9-detailed.log
  - 10-wire_lengths.log
  - reports
  - design.def
  - design.odb
  - design.nl.v
  - design.pnl.v
  - metrics.csv

#-------------------------------------------------------------------------
# Commands
#-------------------------------------------------------------------------

commands:
  # Link inputs to OpenLANE
  - mkdir -p $OPENLANE_DIR/designs/$DESIGN/
  - ln -sf `pwd`/inputs/design.odb $OPENLANE_DIR/0
  # Run step
  - cd $OPENLANE_DIR
  - make run_step OPENLANE_STEP=routing
  - cd -
  # Link outputs from OpenLANE
  - rm -f outputs/*
  - ln -sf $OPENLANE_DIR/designs/$DESIGN/runs/$FLOW_RUNID/$STEP_NAME/logs/routing/1-resizer_design.log outputs/1-resizer_design.log
  - ln -sf $OPENLANE_DIR/designs/$DESIGN/runs/$FLOW_RUNID/$STEP_NAME/logs/routing/2-rsz_design_sta.log outputs/2-rsz_design_sta.log
  - ln -sf $OPENLANE_DIR/designs/$DESIGN/runs/$FLOW_RUNID/$STEP_NAME/logs/routing/3-resizer_timing.log outputs/3-resizer_timing.log
  - ln -sf $OPENLANE_DIR/designs/$DESIGN/runs/$FLOW_RUNID/$STEP_NAME/logs/routing/4-rsz_timing_sta.log outputs/4-rsz_timing_sta.log
  - ln -sf $OPENLANE_DIR/designs/$DESIGN/runs/$FLOW_RUNID/$STEP_NAME/logs/routing/5-global_write_netlist.log outputs/5-global_write_netlist.log
  - ln -sf $OPENLANE_DIR/designs/$DESIGN/runs/$FLOW_RUNID/$STEP_NAME/logs/routing/7-grt_sta.log outputs/7-grt_sta.log
  - ln -sf $OPENLANE_DIR/designs/$DESIGN/runs/$FLOW_RUNID/$STEP_NAME/logs/routing/8-fill.log outputs/8-fill.log
  - ln -sf $OPENLANE_DIR/designs/$DESIGN/runs/$FLOW_RUNID/$STEP_NAME/logs/routing/9-detailed.log outputs/9-detailed.log
  - ln -sf $OPENLANE_DIR/designs/$DESIGN/runs/$FLOW_RUNID/$STEP_NAME/logs/routing/10-wire_lengths.log outputs/10-wire_lengths.log
  - ln -sf `find $OPENLANE_DIR/designs/$DESIGN/runs/$FLOW_RUNID/$STEP_NAME/results/routing -name "*.def"` outputs/design.def
  - ln -sf `find $OPENLANE_DIR/designs/$DESIGN/runs/$FLOW_RUNID/$STEP_NAME/results/routing -name "*.odb"` outputs/design.odb
  - ln -sf `find $OPENLANE_DIR/designs/$DESIGN/runs/$FLOW_RUNID/$STEP_NAME/results/routing -name "*.nl.v"` outputs/design.nl.v
  - ln -sf `find $OPENLANE_DIR/designs/$DESIGN/runs/$FLOW_RUNID/$STEP_NAME/results/routing -name "*.pnl.v"` outputs/design.pnl.v
  - ln -sf $OPENLANE_DIR/designs/$DESIGN/runs/$FLOW_RUNID/$STEP_NAME/reports/routing/ outputs/reports
  - ln -sf $OPENLANE_DIR/designs/$DESIGN/runs/$FLOW_RUNID/$STEP_NAME/reports/metrics.csv outputs/metrics.csv
