#=========================================================================
# Cadence Genus Metrics
#=========================================================================
# Author : Akash Levy
# Date   : November 1, 2023
#=========================================================================

fullname: Cadence Genus Synth Metrics
category: Logic Synthesis
description: Run metric reporting using Cadence Genus
name: cadence-genus-syn-metrics
container: silimate/eda-docker:latest

#-------------------------------------------------------------------------
# Inputs and Outputs
#-------------------------------------------------------------------------

inputs:
  - config/
  - flow/
  - genus.db

outputs:
  - metrics.csv
  - syn_metrics.log

#-------------------------------------------------------------------------
# Commands
#-------------------------------------------------------------------------

commands:
  - cp inputs/flow/run_flow.tcl inputs/
  - cp inputs/config/*.tcl inputs/
  - genus -no_gui -f START.tcl -log outputs/syn_metrics.log
