#=========================================================================
# LVS using netgen
#=========================================================================
# Author : Priyanka Raina
# Date   : Dec 12, 2020
#

fullname: Netgen LVS
category: DRC/LVS
description: Runs open-source Netgen tool to perform layout vs schematic (LVS) checks
name: open-netgen-lvs

#-------------------------------------------------------------------------
# Inputs and Outputs
#-------------------------------------------------------------------------
inputs:
  - adk
  - design_extracted.spice
  - design.lvs.v

outputs:
  - lvs_results.log

#-------------------------------------------------------------------------
# Parameters
#-------------------------------------------------------------------------

parameters:
  design_name: undefined

commands:
  - sh run_lvs.sh

preconditions:
  - assert Tool('netgen')