#=========================================================================
# Cadence Genus Synthesis Flow
#=========================================================================
# Author : Akash Levy
# Date   : November 1, 2023
# Notes  : This runs the Cadence Genus flow using the generated scripts
#=========================================================================

fullname: Cadence Genus Synthesis Flow
category: Logic Synthesis
description: Generate a Cadence block flow using Flowkit
name: cadence-genus-flow
container: silimate/eda-docker:latest

#-------------------------------------------------------------------------
# Inputs and Outputs
#-------------------------------------------------------------------------

inputs:
  - constraints/
  - flow/
  - rtl/
  - design_config.tcl
  - flow_config.tcl
  - genus_config.tcl
  - mmmc_config.tcl
  - metric_config.yaml
  - run_flow.tcl

outputs:
  - constraints/
  - scripts/
  - dbs/
  - fv/
  - genus.db
  - design.v.gz
  - design.g.gz
  - design.lef.taf.gz
  - design.change_names.rpt
  - synthesis.log

#-------------------------------------------------------------------------
# Commands
#-------------------------------------------------------------------------

commands:
  - genus -no_gui -f START.tcl -log outputs/synthesis.log
  - mkdir -p outputs/constraints/
  - mkdir -p outputs/scripts/
  - mv dbs/syn_generic.block_finish.db outputs/dbs/syn_generic.db
  - mv dbs/syn_map.block_finish.db outputs/dbs/syn_map.db
  - mv dbs/genus.db outputs/genus.db
  - mv dbs/syn_opt/*.v.gz outputs/design.v.gz
  - mv dbs/syn_opt/*.g.gz outputs/design.g.gz
  - mv dbs/syn_opt/*.lec.taf.gz outputs/design.lec.taf.gz
  - mv dbs/syn_opt/*.sdc outputs/constraints/
  - mv dbs/syn_opt/*.tcl outputs/scripts/
  - mv fv/ outputs/
  - mv reports/syn_opt/design.change_names.rpt outputs/design.change_names.rpt