#=========================================================================
# Cadence Genus Synthesis Flow
#=========================================================================
# Author : Akash Levy
# Date   : November 1, 2023
# Notes  : This runs the Cadence Genus flow using the generated scripts
#=========================================================================

fullname: Cadence Genus Synthesis Flow
category: Logic Synthesis
description: Generate a Cadence block flow using Flowkit
name: cadence-genus-flow
container: silimate/eda-docker:latest

#-------------------------------------------------------------------------
# Inputs and Outputs
#-------------------------------------------------------------------------

inputs:
  - constraints/
  - flow/
  - design_config.tcl
  - genus_config.tcl
  - mmmc_config.tcl
  - metric_config.yaml
  - run_flow.tcl

outputs:
  - synthesis.log

#-------------------------------------------------------------------------
# Commands
#-------------------------------------------------------------------------

commands:
  - genus -no_gui -f START.tcl -log outputs/synthesis.log