#=========================================================================
# Cadence Genus Synthesis Flow
#=========================================================================
# Author : Akash Levy
# Date   : November 1, 2023
#=========================================================================

fullname: Cadence LEC Flow
category: LEC
description: Runs Cadence LEC flow
name: cadence-lec-flow
container: silimate/eda-docker:latest

#-------------------------------------------------------------------------
# Inputs and Outputs
#-------------------------------------------------------------------------

inputs:
  - config/
  - flow/
  - fv/

outputs:
  - lec.log

#-------------------------------------------------------------------------
# Commands
#-------------------------------------------------------------------------

commands:
  - cp inputs/flow/run_flow.tcl inputs/
  - cp inputs/config/*.tcl inputs/
  - genus -wait 10 -no_gui -f START.tcl -log outputs/lec.log
