name: log-importer
fullname: Import Logs to Database
description: Import logs to database
category: Logs/Metrics

# Trigger on all done
trigger: all_done

inputs:
  - <inherit>.log

#-------------------------------------------------------------------------
# Commands
#-------------------------------------------------------------------------

commands:
  # POST logs to logs database
  - python post_logs.py
