#=========================================================================
# Cadence Voltus Static Rail Analysis
#=========================================================================
# Author : Alex Carsello
# Date   : April 18, 2023
#

fullname: Cadence Voltus Static Rail
category: Power Integrity
description: Perform static rail analysis with Cadence Voltus
name: cadence-voltus-static-rail-analysis

#-------------------------------------------------------------------------
# Inputs and Outputs
#-------------------------------------------------------------------------

inputs:
  - adk
  - design.checkpoint
  - static_power_analysis_results

#-------------------------------------------------------------------------
# Commands
#-------------------------------------------------------------------------

commands:
  - rm -rf *_
  - voltus -overwrite -64 -nowin -init run_voltus_static_rail_analysis.tcl -log logs/run.log

#-------------------------------------------------------------------------
# Parameters
#-------------------------------------------------------------------------

parameters:
  design_name: undefined

#-------------------------------------------------------------------------
# Debug
#-------------------------------------------------------------------------

debug:
  - voltus -overwrite -64
    -init run_debug.tcl
    -log logs/debug.log


#-------------------------------------------------------------------------
# Assertions
#-------------------------------------------------------------------------

preconditions:

  - assert Tool( 'voltus' )                               # tool check
  - assert File( 'inputs/adk' )                           # must exist
  - assert File( 'inputs/static_power_analysis_results' ) # must exist

postconditions:
  - |
    import glob
    for results_file in glob.glob('**_static_rail/*/results', recursive=True):
        assert 'PASSED !' in File(results_file)
