name: openlane-yosys-synthesis
fullname: OpenLane Yosys Synthesis
description: OpenLane logic synthesis using Yosys
category: Logic Synthesis

inputs:
  - design.v
  - design.sdc
  - config.json

outputs:
  - 1-synthesis.log
  - 2-sta.log
  - reports
  - design.syn.v
  - design.sdf

#-------------------------------------------------------------------------
# Commands
#-------------------------------------------------------------------------

commands:
  # Link inputs to OpenLANE
  - mkdir -p $OPENLANE_DIR/designs/$DESIGN/src/
  - ln -sf `pwd`/inputs/design.v $OPENLANE_DIR/designs/$DESIGN/src/design.v
  - ln -sf `pwd`/inputs/design.sdc $OPENLANE_DIR/designs/$DESIGN/src/design.sdc
  - ln -sf `pwd`/inputs/config.json $OPENLANE_DIR/designs/$DESIGN/config.json
  # Run step
  - cd $OPENLANE_DIR
  - make run_step OPENLANE_STEP=synthesis
  - cd -
  # Link outputs from OpenLANE
  - rm -f outputs/*
  - ln -sf $OPENLANE_DIR/designs/$DESIGN/runs/$FLOW_RUNID/$STEP_NAME/logs/synthesis/1-synthesis.log outputs/1-synthesis.log
  - ln -sf $OPENLANE_DIR/designs/$DESIGN/runs/$FLOW_RUNID/$STEP_NAME/logs/synthesis/2-sta.log outputs/2-sta.log
  - ln -sf $OPENLANE_DIR/designs/$DESIGN/runs/$FLOW_RUNID/$STEP_NAME/reports/synthesis/ outputs/reports
  - ln -sf `find $OPENLANE_DIR/designs/$DESIGN/runs/$FLOW_RUNID/$STEP_NAME/results/synthesis -name "*.v"` outputs/design.syn.v
  - ln -sf `find $OPENLANE_DIR/designs/$DESIGN/runs/$FLOW_RUNID/$STEP_NAME/results/synthesis -name "*.sdf"` outputs/design.sdf
