name: openlane-verilator-lint
fullname: OpenLane Verilator Lint
description: OpenLane Verilator Lint
category: Linting

inputs:
  - design.v
  - config.json

outputs:
  - 1-linter.log

#-------------------------------------------------------------------------
# Commands
#-------------------------------------------------------------------------

commands:
  # Link inputs to OpenLANE
  - mkdir -p $OPENLANE_DIR/designs/$DESIGN/src/
  - ln -sf `pwd`/inputs/design.v $OPENLANE_DIR/designs/$DESIGN/src/design.v
  - ln -sf `pwd`/inputs/config.json $OPENLANE_DIR/designs/$DESIGN/config.json
  # Run step
  - cd $OPENLANE_DIR
  - make run_step OPENLANE_STEP=verilator_lint_check
  - cd -
  # Link outputs from OpenLANE
  - rm -f outputs/*
  - ln -sf $OPENLANE_DIR/designs/$DESIGN/runs/$FLOW_RUNID/$STEP_NAME/logs/synthesis/linter.log outputs/1-linter.log
