#=========================================================================
# Cadence Flow Setup
#=========================================================================
# Author : Akash Levy
# Date   : November 1, 2023
#=========================================================================

fullname: Cadence Flow Setup
category: Flow Setup
description: Generate a Cadence flow using Flowkit
name: cadence-flow-setup
container: silimate/eda-docker:latest

#-------------------------------------------------------------------------
# Inputs and Outputs
#-------------------------------------------------------------------------

inputs:
  - constraint_modes.tcl
  - mmmc_config.pdk.tcl

outputs:
  - config/
  - flow/
  - setup.log

#-------------------------------------------------------------------------
# Commands
#-------------------------------------------------------------------------

commands:
  - echo Generating the MMMC config file...
  - cp inputs/mmmc_config.pdk.tcl outputs/mmmc_config.tcl
  - cat inputs/constraint_modes.tcl >> outputs/mmmc_config.tcl
  - echo
  - echo Generating the flow template...
  - genus -no_gui -f START.tcl -log outputs/setup.log
  - echo
  - echo Generating the design_config.tcl file...
  - cp outputs/design_config.template outputs/design_config.tcl
  - sed -i 's/read_physical/# read_physical/' outputs/design_config.tcl # TODO: add in physical synthesis support
  - sed -i 's/<< PLACEHOLDER:\ PHYSICAL DATA LOAD OPTIONS >>/inputs\/design.def/' outputs/design_config.tcl
  - sed -i 's/<< PLACEHOLDER:\ DESIGN HDL LOAD OPTIONS >>/\-f inputs\/rtl\/design.f/' outputs/design_config.tcl
  - sed -i 's/<< PLACEHOLDER:\ ELABORATION OPTIONS >>/'"$design"'/' outputs/design_config.tcl
  - sed -i 's/read_power_intent/# read_power_intent/' outputs/design_config.tcl # TODO: add in UPF support
  - sed -i 's/<< PLACEHOLDER:\ POWER INTENT LOAD OPTIONS >>/inputs\/upf\/design.upf/' outputs/design_config.tcl
  - echo
  - echo Generating the flow_config.tcl file...
  - cp outputs/flow_config.template outputs/flow_config.tcl
  - sed -i 's/<< PLACEHOLDER:\ LEC SYN_MAP SCRIPT OPTIONS >>/'"$lec_options"'/' outputs/flow_config.tcl
  - sed -i 's/<< PLACEHOLDER:\ LEC SYN_OPT SCRIPT OPTIONS >>/'"$lec_options"'/' outputs/flow_config.tcl
  - echo
  - echo Reorganizing outputs...
  - mv outputs/run_flow.tcl outputs/flow/
  - mkdir -p outputs/config/
  - mv outputs/*_config.* outputs/config/

#-------------------------------------------------------------------------
# Parameters
#-------------------------------------------------------------------------

parameters:
  design: top_design_name
  tools: genus lec
  features: report_lec
  lec_options: -verbose -no_dft -no_exit
