#=========================================================================
# Cadence Genus Tech Mapping
#=========================================================================
# Author : Akash Levy
# Date   : November 1, 2023
#=========================================================================

fullname: Cadence Genus Tech Mapping
category: Logic Synthesis
description: Run technology mapping using Cadence Genus
name: cadence-genus-syn-map
container: silimate/eda-docker:latest

#-------------------------------------------------------------------------
# Inputs and Outputs
#-------------------------------------------------------------------------

inputs:
  - config/
  - flow/
  - syn_generic.db

outputs:
  - config/
  - flow/
  - fv/
  - syn_map.db
  - syn_map.log

#-------------------------------------------------------------------------
# Commands
#-------------------------------------------------------------------------

commands:
  - cp inputs/flow/run_flow.tcl inputs/
  - cp inputs/config/*.tcl inputs/
  - genus -no_gui -f START.tcl -log outputs/syn_map.log
  - cp -r inputs/config outputs/config
  - cp -r inputs/flow outputs/flow
  - mv dbs/* outputs/
  - mv fv/ outputs/
