#=========================================================================
# Config Plugin
#=========================================================================
# Author : Akash Levy
# Date   : December 1, 2023
#=========================================================================

fullname: Config Plugin
category: Helper
description: Inject a configuration plugin
name: config-plugin

#-------------------------------------------------------------------------
# Inputs and Outputs
#-------------------------------------------------------------------------

inputs:
  - plugin/
  - config/

outputs:
  - config/

#-------------------------------------------------------------------------
# Commands
#-------------------------------------------------------------------------

commands:
  - cp -rf plugin/* config/
