#=========================================================================
# Convert ICC TCL commands to Innovus TCL
#=========================================================================
# Author : Kartik Prabhu
# Date   : September 21, 2020
#

fullname: Synopsys ICC ECO to Innovus
category: Helper
description: Convert Synopsys ICC TCL commands to Cadence Innovus TCL for ECO
name: open-icc2innovus

#-------------------------------------------------------------------------
# Inputs and Outputs
#-------------------------------------------------------------------------

inputs:
  - icc_eco.tcl

outputs:
  - innovus_eco.tcl

#-------------------------------------------------------------------------
# Commands
#-------------------------------------------------------------------------

commands:
  - python3 icc2innovus.py
