#=========================================================================
# Cadence Genus Stylus Flow Setup
#=========================================================================
# Author : Akash Levy
# Date   : November 1, 2023
#=========================================================================

fullname: Cadence Stylus Flow Setup
category: Flow Setup
description: Generate a Cadence Stylus flow using Flowkit
name: cadence-stylus-flow-setup
container: silimate/eda-docker:latest

#-------------------------------------------------------------------------
# Inputs and Outputs
#-------------------------------------------------------------------------

inputs:
  - config/

outputs:
  - config/
  - flow/
  - setup.log

#-------------------------------------------------------------------------
# Commands
#-------------------------------------------------------------------------

commands:
  - echo Generating the flow template...
  - genus -wait 10 -no_gui -f START.tcl -log outputs/setup.log
  - echo
  - echo Generating the flow_config.tcl file...
  - cp outputs/flow_config.template outputs/flow_config.tcl
  - echo
  - echo Removing references to Cadence scheduler...
  - sed -i 's/schedule_[a-z_]+//' outputs/flow/common_flows.tcl
  - echo
  - echo Reorganizing outputs...
  - mkdir -p outputs/config/
  - mv outputs/*_config.* outputs/config/
  - cp -rf inputs/config/* outputs/config/ # overwrite the default config files with the user's config files

#-------------------------------------------------------------------------
# Parameters
#-------------------------------------------------------------------------

parameters:
  tools: genus lec innovus
  features: dft_simple report_static_ir report_dynamic_ir 
