#=========================================================================
# Cadence Flow Setup
#=========================================================================
# Author : Akash Levy
# Date   : November 1, 2023
#=========================================================================

fullname: Cadence Flow Setup
category: Flow Setup
description: Generate a Cadence Stylus flow
name: cadence-stylus-flow-setup
container: silimate/eda-docker:latest

#-------------------------------------------------------------------------
# Inputs and Outputs
#-------------------------------------------------------------------------

outputs:
  - config/
  - flow/
  - setup.log

#-------------------------------------------------------------------------
# Commands
#-------------------------------------------------------------------------

commands:
  - mkdir -p outputs/config/
  - echo Generating the flow template...
  - genus -wait 10 -no_gui -f START.tcl -log outputs/setup.log
  - echo
  - echo Generating the *_config.tcl and *.yaml files...
  - cp outputs/design_config.template outputs/config/design_config.tcl
  - cp outputs/flow_config.template outputs/config/flow_config.tcl
  - cp outputs/flow.yaml_template outputs/config/flow.yaml
  - cp outputs/setup.yaml_template outputs/config/setup.yaml
  - for tool in $tools; do cp outputs/${tool}_config.template outputs/config/${tool}_config.tcl; done
  - echo
  - echo Removing references to Cadence scheduler...
  - sed -i 's/schedule_[a-z_]*//' outputs/flow/common_flows.tcl

#-------------------------------------------------------------------------
# Parameters
#-------------------------------------------------------------------------

parameters:
  tools: genus lec innovus
  flow_features: dft_simple report_static_ir report_dynamic_ir
