#=========================================================================
# Cadence Innovus PD Flow
#=========================================================================
# Author : Akash Levy
# Date   : November 1, 2023
#=========================================================================

fullname: Cadence Innovus PD Flow
category: Physical Design
description: Runs full Cadence Innovus block physical design (PD) flow with Stylus
name: cadence-innovus-stylus-pd-flow
container: silimate/eda-docker:latest

#-------------------------------------------------------------------------
# Inputs and Outputs
#-------------------------------------------------------------------------

inputs:
  - config/
  - flow/
  - pdk/
  - floorplan/
  - genus.db

outputs:
  - config/
  - flow/
  - pdk/
  - innovus.db
  - innovus.log

#-------------------------------------------------------------------------
# Commands
#-------------------------------------------------------------------------

commands:
  - echo Copying inputs to outputs...
  - cp -r inputs/config/ outputs/config/
  - cp -r inputs/flow/ outputs/flow/
  - cp -r inputs/pdk/ outputs/pdk/
  - echo
  - echo Setting up configs...
  - cp -r inputs/floorplan/ .
  - cp inputs/config/*.tcl inputs/
  - cp inputs/config/*.yaml inputs/
  - echo
  - echo Running the physical design flow...
  - innovus -stylus -wait 10 -no_gui -files START.tcl -log outputs/innovus.log
