#=========================================================================
# Add Files to Directory
#=========================================================================
# Author : Akash Levy
# Date   : November 1, 2023
#=========================================================================

name: utility-add-files-to-dir
fullname: Add Files to Directory
description: Add files to a directory
category: Helper

#-------------------------------------------------------------------------
# Inputs and Outputs
#-------------------------------------------------------------------------

inputs:
  - directory/
  - files_to_add/

outputs:
  - directory/

#-------------------------------------------------------------------------
# Commands
#-------------------------------------------------------------------------

commands:
  - cp -Lrf inputs/directory/ outputs/
  - ln -sf inputs/files_to_add/* outputs/directory/
