name: input-files-from-git
fullname: File(s) from Git
description: Get file(s) from a git repository
category: Inputs

commands:
  - "[[ -e /app/share/.ssh ]] && cp -rf /app/share/.ssh ~"
  - git config --global safe.directory '*'
  - git clone -b $git_branch --single-branch --depth $git_clone_depth $git_url repo
  - cd repo; git checkout $git_commit; cd ..
  - mkdir -p outputs

parameters:
  git_url:
    name: Git URL 
  git_branch:
    name: Git Branch
    value: main
  git_commit:
    name: Git Commit Hash or Tag
    value: HEAD
  git_clone_depth:
    name: Git Clone Depth
    value: 1
