name: openroad-metrics
fullname: OpenROAD Metrics
description: Parse OpenROAD reports and post metrics to database
category: Logs/Metrics

inputs:
  - design.rpt
  - synth_stat.rpt

#-------------------------------------------------------------------------
# Commands
#-------------------------------------------------------------------------

commands:
  # POST metrics to metrics database
  - python post_metrics.py
