#=========================================================================
# Cadence Genus Stylus Synthesis Flow
#=========================================================================
# Author : Akash Levy
# Date   : November 1, 2023
#=========================================================================

fullname: Cadence Genus Stylus Synthesis Flow
category: Logic Synthesis
description: Runs full Cadence Genus block synthesis flow with Stylus
name: cadence-genus-stylus-syn-flow
container: silimate/eda-docker:latest

#-------------------------------------------------------------------------
# Inputs and Outputs
#-------------------------------------------------------------------------

inputs:
  - config/
  - constraints/
  - flow/
  - pdk/
  - rtl/

outputs:
  - config/
  - flow/
  - scripts/
  - dbs/
  - fv/
  - genus.db
  - design.v.gz
  - design.g.gz
  - synthesis.log
  - pdk/
  - rtl/

#-------------------------------------------------------------------------
# Commands
#-------------------------------------------------------------------------

commands:
  - echo Copying inputs to outputs...
  - cp -r inputs/config outputs/config
  - cp -r inputs/flow outputs/flow
  - cp -r inputs/pdk outputs/pdk
  - cp -r inputs/rtl/ outputs/rtl/
  - cp -r inputs/constraints/ .
  - echo
  - echo Setting up inputs...
  - cp inputs/config/*.tcl inputs/
  - cp inputs/config/*.yaml inputs/
  - echo
  - echo Running the synthesis flow...
  - genus -wait 10 -no_gui -f START.tcl -log outputs/synthesis.log
  - echo
  - echo Reorganizing outputs...
  - mkdir -p outputs/constraints/
  - mkdir -p outputs/scripts/
  - mkdir -p outputs/dbs/
  - mv dbs/syn_generic.block_finish.db outputs/dbs/syn_generic.db
  - mv dbs/syn_map.block_finish.db outputs/dbs/syn_map.db
  - mv genus.cdb/syn/*.db outputs/genus.db
  - mv genus.cdb/cmn/*.v.gz outputs/design.v.gz
  - mv genus.cdb/cmn/*.g.gz outputs/design.g.gz
  - mv fv/ outputs/
