name: openroad-yosys-synthesis
fullname: OpenROAD Yosys Synthesis
description: OpenROAD logic synthesis using Yosys
category: Logic Synthesis
container: silimate/openroad:latest

inputs:
  - src/
  - constraint.sdc

outputs:
  - 1_1_yosys.log
  - 1_synth.v
  - synth_check.log
  - synth_stat.rpt
  - 1_Post_synthesis.rpt

#-------------------------------------------------------------------------
# Parameters
#-------------------------------------------------------------------------

parameters:
  DESIGN_NAME: gcd
  PLATFORM: nangate45

  VERILOG_FILES: src/gcd.v
  ABC_AREA: 1

#-------------------------------------------------------------------------
# Commands
#-------------------------------------------------------------------------

commands:
  # Link inputs to OpenROAD
  - export OUTPUTS_DIR=`pwd`/outputs
  - ln -s `pwd`/inputs/src /OpenROAD-flow-scripts/flow/
  - ln -s `pwd`/inputs/constraint.sdc /OpenROAD-flow-scripts/flow/constraint.sdc
  - cp -f `pwd`/inputs/constraint.sdc /OpenROAD-flow-scripts/flow/designs/nangate45/gcd/constraint.sdc
  - export SDC_FILE=./constraint.sdc
  - cd /OpenROAD-flow-scripts/flow/
  - make synth RESULTS_DIR=$OUTPUTS_DIR REPORTS_DIR=$OUTPUTS_DIR LOG_DIR=$OUTPUTS_DIR
  - make do-synth-report RESULTS_DIR=$OUTPUTS_DIR REPORTS_DIR=$OUTPUTS_DIR LOG_DIR=$OUTPUTS_DIR
  - mv $OUTPUTS_DIR/synth_check.txt $OUTPUTS_DIR/synth_check.log
  - mv $OUTPUTS_DIR/synth_stat.txt $OUTPUTS_DIR/synth_stat.rpt
