#=========================================================================
# Cadence CSV Metrics
#=========================================================================
# Author : Akash Levy
# Date   : November 1, 2023
#=========================================================================

name: cadence-csv-metrics
fullname: Cadence Metrics
description: Post Cadence CSV metrics to database
category: Logs/Metrics

inputs:
  - metrics.csv

#-------------------------------------------------------------------------
# Commands
#-------------------------------------------------------------------------

commands:
  # POST metrics to metrics database
  - python post_metrics.py
