name: openlane-floorplan
fullname: OpenLane Floorplan/Power Setup
description: OpenLane run floorplanning step, I/O placement, power planning, and tapcell insertion
category: "PD: Floorplan"

inputs:
  - design.syn.v
  - pin_order.cfg

outputs:
  - 1-init.log
  - 2-place_io.log
  - 3-tap.log
  - 4-pdn.log
  - core_area.rpt
  - die_area.rpt
  - design.def
  - design.odb
  - metrics.csv

#-------------------------------------------------------------------------
# Commands
#-------------------------------------------------------------------------

commands:
  # Link inputs to OpenLANE
  - mkdir -p $OPENLANE_DIR/designs/$DESIGN/
  - ln -sf `pwd`/inputs/design.syn.v $OPENLANE_DIR/0
  - ln -sf `pwd`/inputs/pin_order.cfg $OPENLANE_DIR/designs/$DESIGN/pin_order.cfg
  # Run step
  - cd $OPENLANE_DIR
  - make run_step OPENLANE_STEP=floorplan
  - cd -
  # Link outputs from OpenLANE
  - rm -f outputs/*
  - ln -sf $OPENLANE_DIR/designs/$DESIGN/runs/$FLOW_RUNID/$STEP_NAME/logs/floorplan/1-initial_fp.log outputs/1-init.log
  - ln -sf $OPENLANE_DIR/designs/$DESIGN/runs/$FLOW_RUNID/$STEP_NAME/logs/floorplan/2-place_io.log outputs/2-place_io.log
  - ln -sf $OPENLANE_DIR/designs/$DESIGN/runs/$FLOW_RUNID/$STEP_NAME/logs/floorplan/3-tap.log outputs/3-tap.log
  - ln -sf $OPENLANE_DIR/designs/$DESIGN/runs/$FLOW_RUNID/$STEP_NAME/logs/floorplan/4-pdn.log outputs/4-pdn.log
  - ln -sf $OPENLANE_DIR/designs/$DESIGN/runs/$FLOW_RUNID/$STEP_NAME/reports/floorplan/1-initial_fp_core_area.rpt outputs/core_area.rpt
  - ln -sf $OPENLANE_DIR/designs/$DESIGN/runs/$FLOW_RUNID/$STEP_NAME/reports/floorplan/1-initial_fp_die_area.rpt outputs/die_area.rpt
  - ln -sf $OPENLANE_DIR/designs/$DESIGN/runs/$FLOW_RUNID/$STEP_NAME/reports/metrics.csv outputs/metrics.csv
  - ln -sf `find $OPENLANE_DIR/designs/$DESIGN/runs/$FLOW_RUNID/$STEP_NAME/results/floorplan -name "*.def"` outputs/design.def
  - ln -sf `find $OPENLANE_DIR/designs/$DESIGN/runs/$FLOW_RUNID/$STEP_NAME/results/floorplan -name "*.odb"` outputs/design.odb
