#=========================================================================
# Cadence Genus Generic Synthesis
#=========================================================================
# Author : Akash Levy
# Date   : November 1, 2023
#=========================================================================

fullname: Cadence Genus Generic Synth
category: Logic Synthesis
description: Run generic synthesis using Cadence Genus
name: cadence-genus-syn-generic
container: silimate/eda-docker:latest

#-------------------------------------------------------------------------
# Inputs and Outputs
#-------------------------------------------------------------------------

inputs:
  - config/
  - constraints/
  - flow/
  - rtl/

outputs:
  - config/
  - flow/
  - syn_generic.db
  - syn_generic.log

#-------------------------------------------------------------------------
# Commands
#-------------------------------------------------------------------------

commands:
  - cp -r inputs/config outputs/config
  - cp -r inputs/flow outputs/flow
  - cp inputs/flow/run_flow.tcl inputs/
  - cp inputs/config/*.tcl inputs/
  - genus -wait 10 -no_gui -f START.tcl -log outputs/syn_generic.log
  - mv dbs/* outputs/
