#=========================================================================
# Cadence Genus Generic Synthesis
#=========================================================================
# Author : Akash Levy
# Date   : November 1, 2023
#=========================================================================

fullname: Cadence Genus Generic Synthesis
category: Logic Synthesis
description: Run generic library synthesis using Cadence Genus
name: cadence-genus-syn-generic
container: silimate/eda-docker:latest

#-------------------------------------------------------------------------
# Inputs and Outputs
#-------------------------------------------------------------------------

inputs:
  - config/
  - constraints/
  - flow/
  - rtl/

outputs:
  - config/
  - flow/
  - syn_generic.log

#-------------------------------------------------------------------------
# Commands
#-------------------------------------------------------------------------

commands:
  - cp inputs/flow/run_flow.tcl inputs/
  - cp inputs/config/*.tcl inputs/
  - genus -no_gui -f START.tcl -log outputs/syn_generic.log
  - cp -r inputs/config outputs/config
  - cp -r inputs/flow outputs/flow